export interface Achievement {
  id: string
  title: string
  description: string
  icon: string
  category: 'combat' | 'discipline' | 'mastery' | 'wealth'
  rewardXP: number
  rewardCoins: number
  isUnlocked: boolean
  progress: number
  maxProgress: number
  unlockedAt?: string
}

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_blood',
    title: 'First Blood',
    description: 'Complete your first ever real-world task.',
    icon: '⚔️',
    category: 'combat',
    rewardXP: 50,
    rewardCoins: 5,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'novice_striker',
    title: 'Trial Novice',
    description: 'Complete 5 daily quests.',
    icon: '🛡️',
    category: 'discipline',
    rewardXP: 75,
    rewardCoins: 10,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'veteran_slayer',
    title: 'Veteran Slayer',
    description: 'Complete 15 daily quests.',
    icon: '🏆',
    category: 'discipline',
    rewardXP: 150,
    rewardCoins: 20,
    isUnlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'coder_archmage',
    title: 'Archmage of Code',
    description: 'Complete 5 Intellect/Coding trials.',
    icon: '🧠',
    category: 'mastery',
    rewardXP: 100,
    rewardCoins: 15,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'iron_temple',
    title: 'Iron Temple Titan',
    description: 'Complete 5 Strength/Gym workout trials.',
    icon: '💪',
    category: 'mastery',
    rewardXP: 100,
    rewardCoins: 15,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'vitality_monk',
    title: 'Vitality Monk',
    description: 'Complete 5 Health & Wellness trials.',
    icon: '❤️',
    category: 'mastery',
    rewardXP: 100,
    rewardCoins: 15,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'kindled_streak',
    title: 'Kindled Flame',
    description: 'Achieve a 3-day daily streak.',
    icon: '🔥',
    category: 'discipline',
    rewardXP: 100,
    rewardCoins: 10,
    isUnlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'unbroken_will',
    title: 'Unbroken Will',
    description: 'Achieve a 7-day daily streak without dropping the bonfire.',
    icon: '⚡',
    category: 'discipline',
    rewardXP: 250,
    rewardCoins: 25,
    isUnlocked: false,
    progress: 0,
    maxProgress: 7,
  },
  {
    id: 'sovereign_level',
    title: 'Ascendant Sovereign',
    description: 'Reach Character Level 5.',
    icon: '👑',
    category: 'mastery',
    rewardXP: 200,
    rewardCoins: 20,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'patron_bazaar',
    title: 'Royal Patron',
    description: 'Purchase your first item in the Royal Bazaar.',
    icon: '🛍️',
    category: 'wealth',
    rewardXP: 50,
    rewardCoins: 5,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'dragon_treasury',
    title: "Dragon's Treasury",
    description: 'Accumulate 50 gold coins in your treasury.',
    icon: '🪙',
    category: 'wealth',
    rewardXP: 150,
    rewardCoins: 15,
    isUnlocked: false,
    progress: 0,
    maxProgress: 50,
  },
  {
    id: 'master_shaders',
    title: 'Master of Shaders',
    description: 'Equip an environmental ambient theme or crest badge.',
    icon: '🎨',
    category: 'wealth',
    rewardXP: 75,
    rewardCoins: 10,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
]
